CREATE TABLE [dbo].[AttendanceType](
  [A_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
  [A_Name] [varchar](45) NOT NULL UNIQUE,
  PRIMARY KEY CLUSTERED
(
[A_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[RegistrationType]
(
    [R_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
PRIMARY KEY CLUSTERED
(
[R_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[Lector]
(
  [L_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
  [L_Name] [varchar](45) NOT NULL,
PRIMARY KEY CLUSTERED
(
[L_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[Campus]
(
	[C_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
	[C_Name] [varchar](45) NOT NULL,
	[C_City] [varchar](45) NOT NULL,
PRIMARY KEY CLUSTERED
(
[C_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[CourseEventStudent]
(
	[CES_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
	[CES_CourseEventId] [int] NOT NULL,
	[CES_RegistrationTypeId] [int] NOT NULL,
    [CES_AttendanceTypeId] [int] NOT NULL,
    
PRIMARY KEY CLUSTERED
(
[CES_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [dbo].[CourseEvent]
(
  [CE_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
  [CE_CourseId] [int] NOT NULL,
PRIMARY KEY CLUSTERED
(
[CE_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[Course]
(
  [C_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
  [C_LectorId] [int] NOT NULL,
  [C_Name] [varchar](45) NOT NULL,
PRIMARY KEY CLUSTERED
(
[C_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[Classroom]
(
  [CR_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
  [CR_CampusId] [int] NOT NULL,
  [CR_Name] [varchar](45) NOT NULL,
PRIMARY KEY CLUSTERED
(
[CR_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[StudentGroup]
(
  [SG_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
  [SG_StudentId] [int] NOT NULL,

PRIMARY KEY CLUSTERED
(
[SG_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[Group]
(
  [G_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
  [G_Name] [varchar](45) NOT NULL,
  [G_Start] [date] NOT NULL,
  [G_Stop] [date] NOT NULL,
PRIMARY KEY CLUSTERED
(
[G_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [dbo].[Student]
(
  [S_Id] [int] IDENTITY(1,1) NOT NULL UNIQUE,
  [S_Barcode] [varchar](13) NOT NULL,
  [S_Name] [varchar](45) NOT NULL,
  [S_StudentNmr] [varchar](9) NOT NULL,
  [S_BirthDate][date] NOT NULL,
  [S_Username][varchar](8),
  [S_image][varchar] ,
PRIMARY KEY CLUSTERED
(
[S_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];